version: '2'
services:
  geth:
    image: daocloud.io/daocloud/geth
    cpu_quota: 50000
    restart: on-failure
    environment:
      - WS_SERVER ws://blockchain.daocloud.io:80
      - WS_SECRET daocloud-eth-net-stats-secret
    volumes:
      - ${HOME}/.ethereum/keystore:/root/.ethereum/keystore
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.ethash:/root/.ethash
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  server:
    image: daocloud.io/daocloud/daochain
    cpu_quota: 50000
    restart: on-failure
    environment:
      - ETH_RPC_ENDPOINT = geth:8545
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker:/root/.docker
    ports:
      - "8000:80"
